export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';

export const POSTS_LOADED = 'POSTS_LOADED';
export const START_POSTS_LOADING = 'START_POSTS_LOADING';
export const ERROR_LOADING_POSTS = 'ERROR_LOADING_POSTS';
export const STOP_POSTS_LOADING = 'STOP_POSTS_LOADING';

